name: run the workflow
on:
    repository_dispatch:
        types: ["my-event2"]
    workflow_dispatch:       
        
jobs:
    run-triggered-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: print trigger details
              run: |
                echo "hey hello"
            - name: Checkout code
              uses: actions/checkout@v3    
    
            - name: Read version from package.json using Node.js
              id: read_version
              run: |
                  LATEST_VERSION=$(node -p "require('./package.json').version")
                  echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT 
                  
                  
            - name: Use version in subsequent steps
              run: echo "The latest version from package.json is ${{ steps.read_version.outputs.LATEST_VERSION }}-test"     
              
            - name: Test run
              run: echo "Testingggg heeloo" 
              
            - name: Assign a value to tag type
              id: check_tag_type
              run: |
                  TAG_TYPE = 2024-10    

            - name: Checking if tag if YYYY-MM or monthly-v2
              run: |
                   echo "the tag is ${{ steps.check_tag_type.outputs.TAG_TYPE}}"
