name: Debug
on:
    repository_dispatch:
        types: ["my-event2"]
    workflow_dispatch:

jobs:
    publish:
        name: POC for triggering workflow
        runs-on: ubuntu-latest
        strategy:
            matrix:
                packages: ["./packages/testrepo","./packages/testrepo2"]
        steps:
            - name: Clean up runner
              run: |
                echo "cleaning up previous run"
            - name: Repository dispatch test
              run: |
                echo "I am called!"

            - name: print the details of the packages
              run: |
                echo "the name of the package is ${{ matrix.packages }}"

              
