name: run the workflow
on:
    repository_dispatch:
        types: ["my-event2"]
    workflow_dispatch:       
        
jobs:
    run-triggered-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: print trigger details
              run: |
                echo "hey hello"
            - name: Checkout code
              uses: actions/checkout@v3    
    
            - name: Read version from package.json using Node.js
              id: read_version
              run: |
                  LATEST_VERSION=$(node -p "require('./package.json').version")
                  echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT 
                  
                  
            - name: Use version in subsequent steps
              run: echo "The latest version from package.json is ${{ steps.read_version.outputs.LATEST_VERSION }}-test"     
              
            - name: Test run
              run: echo "Testss heeloo" 
              
            - name: Assign a value to tag type
              id: check_tag_type
               
                  
              run: |
                  CURRENT_TAG=v2.272.3
                  echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_OUTPUT

            - name: Checking if tag if YYYY-MM or monthly-v2
              run: |
                  echo "the tag is ${{ steps.check_tag_type.outputs.CURRENT_TAG}}"

                  if [[ ${{ steps.check_tag_type.outputs.CURRENT_TAG }} =~ ^[0-9]{4}-[0-9]{2}$ ]] || [[ ${{ steps.check_tag_type.outputs.CURRENT_TAG }} == "monthly-v2" ]]; then
                    echo "VALID_FORMAT=true"  >> $GITHUB_OUTPUT
                    echo "The tag format is valid."
                  else
                    echo "VALID_FORMAT=false"  >> $GITHUB_OUTPUT
                    echo "The tag format is not valid."
                  fi