name: Debug
on:
    repository_dispatch:
        types: ["my-event2"]
    workflow_dispatch:

jobs:
    publish:
        name: POC for triggering workflow
        runs-on: ubuntu-latest
        strategy:
            matrix:
                packages: ["./packages/testrepo","./packages/testrepo2"]
        steps:
            - name: Clean up runner
              run: |
                echo "cleaning up previous run"
            - name: Repository dispatch test
              run: |
                echo "I am called!"

            - name: print the details of the packages
              id: abc
              run: |
                echo "the name of the package is ${{ matrix.packages }}"
                LATEST_VERSION=$(node -p "require('./package.json').version")
                echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
            
            # - name: Print the details
            #   run: |
            #       echo "the name is ${{steps.abc.outputs.LATEST_VERSION }}" 
                
            # - name: Read the details for package
            #   id: package_details
            #   run: |
            #     VERSION = $(node -p "require('${{ matrix.packages}}/package.json').version")
            #     NAME = $(node -p "require('${{ matrix.packages}}/package.json').name")
            #     echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
            #     echo "NAME=$NAME" >> $GITHUB_OUTPUT
            
            # - name: Print the details
            #   run: |
            #     echo "the name is ${{steps.package_details.outputs.NAME }}" 
            #     echo "the version is ${{steps.package_details.outputs.VERSION }}"    
              
