name: Debug
on:
    repository_dispatch:
        types: ["my-event2"]
    workflow_dispatch:

jobs:
    publish:
        name: POC for triggering workflow
        runs-on: ubuntu-latest
        steps:
            - name: Clean up runner
              run: |
                echo "cleaning up previous run"
            - name: Repository dispatch test
              run: |
                echo "I am called!"
              
