name: run the workflow
on:
    repository_dispatch:
        types: ["my-event2"]
        
jobs:
    run-triggered-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: print trigger details
              run: |
                echo "hey hello"
                
            - name: Read version from package.json using Node.js
              id: read_version
              run: |
                  version=$(node -p "require('./package.json').version")
                  echo "version=$version" >> $GITHUB_ENV    