name: Testing
on:
    repository_dispatch:
        types: ["my-event3"]
    workflow_dispatch:

jobs:
    publish:
        name: Testing repository dispatch called or not
        runs-on: ubuntu-latest
        steps:
            - name: Clean up runner
              run: |
                echo "cleaning up previous run"
            - name: Repository dispatch test
              run: |
                echo "I am called test!"

            - name: Read version from package.json using Node.js
              id: read_version
              run: |
                LATEST_VERSION=$(node -p "require('./package.json').version")
                echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT   
            
            - name: Use version in subsequent steps
              run: echo "The latest version from package.json is ${{ steps.read_version.outputs.LATEST_VERSION }}-test"     
                  
              
