name: Testing
on:
    repository_dispatch:
        types: ["my-event3"]
    workflow_dispatch:

jobs:
    publish:
        name: Testing repository dispatch called or not
        runs-on: ubuntu-latest
        steps:
            - name: Clean up runner
              run: |
                echo "cleaning up previous run"
            - name: Repository dispatch test
              run: |
                echo "I am called test!"
              
